name: Build single binary executables for multiple architectures

on:
    workflow_dispatch: 

permissions: 
    pull-requests: read
    contents: read


concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    build-image:
        strategy:
            matrix:
              os: [ubuntu-latest, windows-latest, macos-latest]
        name: Build image
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                ls -ltrha .
                