name: Build single binary executables for multiple architectures

on:
    workflow_dispatch: 

permissions: 
    pull-requests: read
    contents: write

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    draft-release:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ github.token }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Draft release
              run: |
                gh release create v0.0.2 --title "Draft 0.0.2" --notes "N/A"
    build-image:
        strategy:
            matrix:
              os: [ubuntu-latest, windows-latest, macos-latest]
        env:
            GH_TOKEN: ${{ github.token }}
        name: Build image
        runs-on: ${{ matrix.os }}
        needs: draft-release
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              shell: bash
              run: |
                python --version
                pip install bdist_pyinstaller toml setuptools
                python singlebinary.py bdist_pyinstaller
                suffix=$(uname)-$(uname -m)
                cp ./build/*/bdist_pyinstaller/eve-* ./eve-$suffix
                gh release upload v0.0.1 --clobber ./eve-$suffix
                
                # gh release create v0.0.1-${{matrix.os}} --title "Draft 0.0.1 ${{matrix.os}}" --notes "Single binary for ${{matrix.os}}" ./build/*/bdist_pyinstaller/eve-*
                # ./build/bdist.linux-x86_64/bdist_pyinstaller/eve-0.0.0
                # ./build/bdist.macosx-10.9-universal2/bdist_pyinstaller/eve-0.0.0
                # ./build\bdist.win-amd64\bdist_pyinstaller\eve-0.0.0.exe

